export const trainingDataShape = {
	endDate: '',
	id: '',
	image: '',
	information: '',
	isComplete: null,
	isOnline: null,
	latitude: '',
	location: '',
	longitude: '',
	name: '',
	rating: 0,
	startDate: '',
	trainer: '',
	userId: '',
}
