export const data1 = [
	{
		createdAt: '2022-08-23T06:37:34.614Z',
		endDate: '2022-10-03T01:57:03.657Z',
		id: '5',
		imageUrl: 'imageUrl 1',
		information: 'lorem ipsum',
		isOnline: false,
		latitude: '110.363331',
		location: 'UGM Kampus',
		longitude: '-7.844740',
		longtitude: 'longtitude 1',
		name: 'Learn Golang',
		period: '2022-09-03T01:57:03.657Z',
		startDate: '2022-09-03T01:57:03.657Z',
		trainerName: 'John Red',
		userId: 'user123',
	},
	{
		createdAt: '2022-08-24T05:19:28.221Z',
		endDate: '25-Aug-2022-04:00',
		id: '6',
		imageUrl: 'imageUrl 6',
		information:
			'cillum adipisicing ex minim non aliquip. Excepteur irure cupidatat eiusmod id ad labore irure.',
		isOnline: false,
		latitude: '234235253',
		location: 'UGM Campus',
		longtitude: '422419221',
		name: 'Learn Networking',
		period: '25-Aug-2022-12:00 - 04:00',
		startDate: '25-Aug-2022-12:00',
		trainerName: 'Jane Doe',
		userId: 'user123',
	},
	{
		createdAt: '2022-08-24T03:45:18.029Z',
		endDate: '05-Aug-2022-01:53',
		id: '7',
		imageUrl: 'imageUrl 7',
		information:
			'Est culpa ullamco esse eu excepteur nulla cupidatat ad excepteur. Nostrud incididunt nulla sunt velit quis proident incididunt eu mollit excepteur. Labore voluptate exercitation quis occaecat elit sunt magna pariatur qui amet proident voluptate sint. Occaecat ea dolore adipisicing excepteur sunt adipisicing sint veniam minim sint enim. Quis ea sit ea eu non. Sit amet Lorem elit id in velit ipsum ',
		isOnline: false,
		latitude: 'asdadsasd',
		location: 'asdadsad',
		longtitude: 'asdadsad',
		name: 'Learn ReactJS',
		period: '04-Aug-2022-01:53 - 01:53',
		startDate: '04-Aug-2022-01:53',
		trainerName: 'asdadsad',
		userId: 'user123',
	},
	{
		createdAt: '2022-08-23T06:37:34.614Z',
		endDate: '2022-10-03T01:57:03.657Z',
		id: '8',
		imageUrl: 'imageUrl 8',
		information: 'lorem ipsum',
		isOnline: true,
		latitude: '110.363331',
		location: 'Kulon Progo Airport',
		longitude: '-7.844740',
		longtitude: 'longtitude 1',
		name: 'Training Tailwind',
		period: '2022-09-03T01:57:03.657Z',
		startDate: '2022-09-03T01:57:03.657Z',
		trainerName: 'Dwayne Johnson',
		userId: 'user123',
	},
]

export const data2 = [
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/c/cf/Angular_full_color_logo.svg',
		name: 'Training Angular',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '9 Jul 2022, 07:00 - 10:00',
		trainerName: 'Juwwita Susati',
		rating: 3,
		aditionalInfo: 'Quis aliqua cupidatat quis ullamco sit ea.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg',
		name: 'Learn ReactJS',
		type: 'Online Class',
		period: '10 Aug 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 5,
		aditionalInfo: 'Velit commodo ipsum nostrud nostrud anim minim esse.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Go_Logo_Blue.svg',
		name: 'Training Golang',
		type: 'Online Class',
		period: '11 Dec 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 2,
		aditionalInfo: 'Ad irure non ex do Exercitation dolore qui elit.',
	},
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg',
		name: 'Learn Typescript',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '11 Jan 2022, 07:00 - 12:00',
		trainerName: 'Johnny Depp',
		rating: 4,
		aditionalInfo: 'Exercitation nostrud irure consectetur duis.',
	},
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/c/cf/Angular_full_color_logo.svg',
		name: 'Training Angular',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '9 Jul 2022, 07:00 - 10:00',
		trainerName: 'Juwwita Susati',
		rating: 3,
		aditionalInfo: 'Quis aliqua cupidatat quis ullamco sit ea.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg',
		name: 'Learn ReactJS',
		type: 'Online Class',
		period: '10 Aug 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 5,
		aditionalInfo: 'Velit commodo ipsum nostrud nostrud anim minim esse.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Go_Logo_Blue.svg',
		name: 'Training Golang',
		type: 'Online Class',
		period: '11 Dec 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 2,
		aditionalInfo: 'Ad irure non ex do Exercitation dolore qui elit.',
	},
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg',
		name: 'Learn Typescript',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '11 Jan 2022, 07:00 - 12:00',
		trainerName: 'Johnny Depp',
		rating: 4,
		aditionalInfo: 'Exercitation nostrud irure consectetur duis.',
	},
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/c/cf/Angular_full_color_logo.svg',
		name: 'Training Angular',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '9 Jul 2022, 07:00 - 10:00',
		trainerName: 'Juwwita Susati',
		rating: 3,
		aditionalInfo: 'Quis aliqua cupidatat quis ullamco sit ea.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg',
		name: 'Learn ReactJS',
		type: 'Online Class',
		period: '10 Aug 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 5,
		aditionalInfo: 'Velit commodo ipsum nostrud nostrud anim minim esse.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Go_Logo_Blue.svg',
		name: 'Training Golang',
		type: 'Online Class',
		period: '11 Dec 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 2,
		aditionalInfo: 'Ad irure non ex do Exercitation dolore qui elit.',
	},
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg',
		name: 'Learn Typescript',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '11 Jan 2022, 07:00 - 12:00',
		trainerName: 'Johnny Depp',
		rating: 4,
		aditionalInfo: 'Exercitation nostrud irure consectetur duis.',
	},
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/c/cf/Angular_full_color_logo.svg',
		name: 'Training Angular',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '9 Jul 2022, 07:00 - 10:00',
		trainerName: 'Juwwita Susati',
		rating: 3,
		aditionalInfo: 'Quis aliqua cupidatat quis ullamco sit ea.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg',
		name: 'Learn ReactJS',
		type: 'Online Class',
		period: '10 Aug 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 5,
		aditionalInfo: 'Velit commodo ipsum nostrud nostrud anim minim esse.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Go_Logo_Blue.svg',
		name: 'Training Golang',
		type: 'Online Class',
		period: '11 Dec 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 2,
		aditionalInfo: 'Ad irure non ex do Exercitation dolore qui elit.',
	},
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg',
		name: 'Learn Typescript',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '11 Jan 2022, 07:00 - 12:00',
		trainerName: 'Johnny Depp',
		rating: 4,
		aditionalInfo: 'Exercitation nostrud irure consectetur duis.',
	},
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/c/cf/Angular_full_color_logo.svg',
		name: 'Training Angular',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '9 Jul 2022, 07:00 - 10:00',
		trainerName: 'Juwwita Susati',
		rating: 3,
		aditionalInfo: 'Quis aliqua cupidatat quis ullamco sit ea.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg',
		name: 'Learn ReactJS',
		type: 'Online Class',
		period: '10 Aug 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 5,
		aditionalInfo: 'Velit commodo ipsum nostrud nostrud anim minim esse.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Go_Logo_Blue.svg',
		name: 'Training Golang',
		type: 'Online Class',
		period: '11 Dec 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 2,
		aditionalInfo: 'Ad irure non ex do Exercitation dolore qui elit.',
	},
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg',
		name: 'Learn Typescript',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '11 Jan 2022, 07:00 - 12:00',
		trainerName: 'Johnny Depp',
		rating: 4,
		aditionalInfo: 'Exercitation nostrud irure consectetur duis.',
	},
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/c/cf/Angular_full_color_logo.svg',
		name: 'Training Angular',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '9 Jul 2022, 07:00 - 10:00',
		trainerName: 'Juwwita Susati',
		rating: 3,
		aditionalInfo: 'Quis aliqua cupidatat quis ullamco sit ea.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg',
		name: 'Learn ReactJS',
		type: 'Online Class',
		period: '10 Aug 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 5,
		aditionalInfo: 'Velit commodo ipsum nostrud nostrud anim minim esse.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Go_Logo_Blue.svg',
		name: 'Training Golang',
		type: 'Online Class',
		period: '11 Dec 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 2,
		aditionalInfo: 'Ad irure non ex do Exercitation dolore qui elit.',
	},
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg',
		name: 'Learn Typescript',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '11 Jan 2022, 07:00 - 12:00',
		trainerName: 'Johnny Depp',
		rating: 4,
		aditionalInfo: 'Exercitation nostrud irure consectetur duis.',
	},
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/c/cf/Angular_full_color_logo.svg',
		name: 'Training Angular',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '9 Jul 2022, 07:00 - 10:00',
		trainerName: 'Juwwita Susati',
		rating: 3,
		aditionalInfo: 'Quis aliqua cupidatat quis ullamco sit ea.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg',
		name: 'Learn ReactJS',
		type: 'Online Class',
		period: '10 Aug 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 5,
		aditionalInfo: 'Velit commodo ipsum nostrud nostrud anim minim esse.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Go_Logo_Blue.svg',
		name: 'Training Golang',
		type: 'Online Class',
		period: '11 Dec 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 2,
		aditionalInfo: 'Ad irure non ex do Exercitation dolore qui elit.',
	},
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg',
		name: 'Learn Typescript',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '11 Jan 2022, 07:00 - 12:00',
		trainerName: 'Johnny Depp',
		rating: 4,
		aditionalInfo: 'Exercitation nostrud irure consectetur duis.',
	},
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/c/cf/Angular_full_color_logo.svg',
		name: 'Training Angular',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '9 Jul 2022, 07:00 - 10:00',
		trainerName: 'Juwwita Susati',
		rating: 3,
		aditionalInfo: 'Quis aliqua cupidatat quis ullamco sit ea.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg',
		name: 'Learn ReactJS',
		type: 'Online Class',
		period: '10 Aug 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 5,
		aditionalInfo: 'Velit commodo ipsum nostrud nostrud anim minim esse.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Go_Logo_Blue.svg',
		name: 'Training Golang',
		type: 'Online Class',
		period: '11 Dec 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 2,
		aditionalInfo: 'Ad irure non ex do Exercitation dolore qui elit.',
	},
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg',
		name: 'Learn Typescript',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '11 Jan 2022, 07:00 - 12:00',
		trainerName: 'Johnny Depp',
		rating: 4,
		aditionalInfo: 'Exercitation nostrud irure consectetur duis.',
	},
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/c/cf/Angular_full_color_logo.svg',
		name: 'Training Angular',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '9 Jul 2022, 07:00 - 10:00',
		trainerName: 'Juwwita Susati',
		rating: 3,
		aditionalInfo: 'Quis aliqua cupidatat quis ullamco sit ea.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg',
		name: 'Learn ReactJS',
		type: 'Online Class',
		period: '10 Aug 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 5,
		aditionalInfo: 'Velit commodo ipsum nostrud nostrud anim minim esse.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Go_Logo_Blue.svg',
		name: 'Training Golang',
		type: 'Online Class',
		period: '11 Dec 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 2,
		aditionalInfo: 'Ad irure non ex do Exercitation dolore qui elit.',
	},
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg',
		name: 'Learn Typescript',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '11 Jan 2022, 07:00 - 12:00',
		trainerName: 'Johnny Depp',
		rating: 4,
		aditionalInfo: 'Exercitation nostrud irure consectetur duis.',
	},
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/c/cf/Angular_full_color_logo.svg',
		name: 'Training Angular',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '9 Jul 2022, 07:00 - 10:00',
		trainerName: 'Juwwita Susati',
		rating: 3,
		aditionalInfo: 'Quis aliqua cupidatat quis ullamco sit ea.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg',
		name: 'Learn ReactJS',
		type: 'Online Class',
		period: '10 Aug 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 5,
		aditionalInfo: 'Velit commodo ipsum nostrud nostrud anim minim esse.',
	},
	{
		image: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Go_Logo_Blue.svg',
		name: 'Training Golang',
		type: 'Online Class',
		period: '11 Dec 2022, 12:00 - 14:00',
		trainerName: 'Bruce wyne',
		rating: 2,
		aditionalInfo: 'Ad irure non ex do Exercitation dolore qui elit.',
	},
	{
		image:
			'https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg',
		name: 'Learn Typescript',
		location: 'Jln. Terserah, Jakarta, Id',
		type: 'Offline Class',
		period: '11 Jan 2022, 07:00 - 12:00',
		trainerName: 'Johnny Depp',
		rating: 4,
		aditionalInfo: 'Exercitation nostrud irure consectetur duis.',
	},
]

export const trasnferMockData = [
	{ chosen: false, key: 0, name: 'Participant 1' },
	{ chosen: false, key: 1, name: 'Participant 2' },
	{ chosen: false, key: 2, name: 'Participant 3' },
	{ chosen: false, key: 3, name: 'Participant 4' },
	{ chosen: false, key: 4, name: 'Participant 5' },
	{ chosen: false, key: 5, name: 'Participant 6' },
	{ chosen: false, key: 6, name: 'Participant 7' },
	{ chosen: false, key: 7, name: 'Participant 8' },
	{ chosen: false, key: 8, name: 'Participant 9' },
	{ chosen: false, key: 9, name: 'Participant 10' },
]

export const transferMockKeys = [2, 1, 9, 7]